name: exchange_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  candlesticks: ^2.1.0
  get: ^4.6.5
  custom_navigation_bar: ^0.8.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: IRANSansMobile
      fonts:
        - asset: assets/fonts/IRANSansMobile.ttf
    - family: IRANSansNum
      fonts:
        - asset: assets/fonts/IRANSansNum.ttf
